# Generated by Django 6.1.1 on 2026-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_name', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('savings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'add a deposit',
                'verbose_name_plural': 'Deposits',
            },
        ),
    ]
